version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: opencart-nginx
    ports:
      - "8085:80"
    volumes:
      - ./opencart/upload:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: opencart-php
    volumes:
      - ./opencart/upload:/var/www/html

  db:
    image: mariadb:10.5
    container_name: opencart-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opencart
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
